// Code generated by github.com/0xys/stylus-go/sdk. DO NOT EDIT.

package main

import sdk "github.com/0xys/stylus-go/sdk"

// export user_entrypoint
func user_entrypoint(args_len uint32) uint32 {
	sdk.Init(args_len)
	defer sdk.Flush()

	cont := &FooContract{}
	cd := sdk.GetCalldata()
	if len(cd) < 4 {
		return 0
	}
	sel := sdk.ToSelector(cd[:4])
	switch sel {
	case uint32(0xc49c36c):
		if !sdk.MsgValue().IsZero() {
			return 0
		}
		sdk.SetPure()
		err := cont.SayHi()
		if err != nil {
			sdk.SetReturnString(err.Error())
			return 0
		}
	case uint32(0xa9059cbb):
		if !sdk.MsgValue().IsZero() {
			return 0
		}
		param0, err := sdk.DecodeAddress(cd[4:36])
		if err != nil {
			sdk.SetReturnString(err.Error())
			return 0
		}
		param1, err := sdk.DecodeU256(cd[36:68])
		if err != nil {
			sdk.SetReturnString(err.Error())
			return 0
		}
		err = cont.Transfer(param0, param1)
		if err != nil {
			sdk.SetReturnString(err.Error())
			return 0
		}
	case uint32(0x5cdf6ad2):
		param0, err := sdk.DecodeUint64(cd[4:36])
		if err != nil {
			sdk.SetReturnString(err.Error())
			return 0
		}
		err = cont.Receive(param0)
		if err != nil {
			sdk.SetReturnString(err.Error())
			return 0
		}
	case uint32(0xb69ef8a8):
		if !sdk.MsgValue().IsZero() {
			return 0
		}
		sdk.SetView()
		ret, err := cont.Balance()
		if err != nil {
			sdk.SetReturnString(err.Error())
			return 0
		}
		sdk.SetReturnBytes(ret.Bytes())
	case uint32(0x23b872dd):
		if !sdk.MsgValue().IsZero() {
			return 0
		}
		param0, err := sdk.DecodeAddress(cd[4:36])
		if err != nil {
			sdk.SetReturnString(err.Error())
			return 0
		}
		param1, err := sdk.DecodeU256(cd[36:68])
		if err != nil {
			sdk.SetReturnString(err.Error())
			return 0
		}
		ret, err := cont.TransferFrom(param0, param1)
		if err != nil {
			sdk.SetReturnString(err.Error())
			return 0
		}
		sdk.SetReturnBytes(ret.Bytes())
	}
	return 0
}

// dummy main is needed
func main() {
	user_entrypoint(0)
}
